version: '3.9'

services:
  app:
    build:
      context: .
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:8080"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_HOST: db
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      ROCKET_API_KEY: ${ROCKET_API_KEY}
      HONEST_API_KEY: ${HONEST_API_KEY}
      SMMCOST_API_KEY: ${SMMCOST_API_KEY}
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      DONWEB_DOMAIN: ${DONWEB_DOMAIN}
      ADMIN_PASS: ${ADMIN_PASS}
      APP_PORT: ${APP_PORT}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0.33
    container_name: easymarketing-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
